// license:BSD-3-Clause
// copyright-holders:Stephen Spiller

#ifndef MAME_VIDEO_COCOVGA_EXTENDED_H
#define MAME_VIDEO_COCOVGA_EXTENDED_H

#pragma once

#include "cocovga_renderer.h"
#include "mc6847_charset.h"

#include <cstddef>
#include <cstdint>
#include <type_traits>

namespace cocovga
{

constexpr std::uint8_t W64_COLUMNS = 64;
constexpr std::uint8_t W64_ROWS = 32;
constexpr std::uint8_t W64_GLYPH_WIDTH = 8;
constexpr std::uint8_t W64_GLYPH_HEIGHT = 12;
constexpr std::uint16_t W64_LOGICAL_BYTES = 2'048;
constexpr std::uint8_t W64_CAPTURE_ROW_BYTES = 32;
constexpr std::uint8_t W64_HOST_LINE_REPEAT = 3;

constexpr std::uint8_t VG6_LOGICAL_WIDTH = 128;
constexpr std::uint8_t VG6_LOGICAL_HEIGHT = 96;
constexpr std::uint8_t VG6_BYTES_PER_ROW = 64;
constexpr std::uint8_t VG6_SCALE_X = 4;
constexpr std::uint8_t VG6_SCALE_Y = 4;

enum class extended_mode : std::uint8_t
{
	NONE,
	W64,
	VG6
};

enum class extended_status : std::uint8_t
{
	OK,
	NO_MODE,
	MODE_INACTIVE,
	INVALID_SURFACE,
	FRAME_UNAVAILABLE,
	FRAME_INCOMPLETE,
	INCONSISTENT_CAPTURE
};

enum class character_layout : std::uint8_t
{
	NATIVE_32,
	W64
};

enum class character_glyph : std::uint8_t
{
	NONE,
	TEXT,
	SEMIGRAPHICS4,
	SEMIGRAPHICS6
};

enum class character_source : std::uint8_t
{
	NONE,
	CHARACTER_ROM,
	LOWERCASE_CHARACTER_ROM,
	UPLOADED_RAM,
	GENERATED
};

// CoCoVGA regenerates the VDG character set from the MC6847 and MC6847T1
// character generator ROMs and selects between the two banks from the font
// register, exactly as the FPGA does.  Each bank holds the ROM glyphs adjusted
// for CoCoVGA's cell: the T1 bank is shifted one row down and one pixel
// towards the left edge of the cell, and the FPGA substitutes its own bitmaps
// for a handful of characters (see cocovga_charrom.h).  The lowercase bank and
// the semigraphics fonts are generated by the FPGA itself and need no ROM.
class character_generator
{
public:
	character_generator() noexcept;

	// Raw character generator ROM images, sized mc6847_charset::INTERNAL_ROM_BYTES
	// and mc6847_charset::T1_ROM_BYTES respectively.  Both are required: the
	// board carries both ROMs, and neither bank can be approximated from the
	// other without changing the glyphs the hardware draws.
	void load(std::uint8_t const *standard_rom, std::uint8_t const *t1_rom) noexcept;

	std::uint8_t text_row(bool t1_font, std::uint8_t character, std::uint8_t row) const noexcept;
	std::uint8_t lowercase_row(bool t1_font, std::uint8_t character, std::uint8_t row) const noexcept;
	std::uint8_t semigraphics4_row(std::uint8_t character, std::uint8_t row) const noexcept;
	std::uint8_t semigraphics6_row(std::uint8_t character, std::uint8_t row) const noexcept;

	// FNV-1a digests of the two expanded text banks.  They identify the ROM
	// images the banks came from without carrying any glyph data, so that a
	// redump of either ROM is detected rather than silently changing output.
	std::uint64_t text_bank_digest(bool t1_font) const noexcept;

	// Used when no ROM-backed generator has been attached yet.  Every glyph is
	// blank, and the digests differ from any loaded bank.
	static character_generator const &blank() noexcept;

private:
	static constexpr std::size_t TEXT_GLYPHS = 64;
	static constexpr std::size_t SEMIGRAPHICS4_GLYPHS = mc6847_charset::SEMIGRAPHICS4_GLYPH_COUNT;
	static constexpr std::size_t SEMIGRAPHICS6_GLYPHS = mc6847_charset::SEMIGRAPHICS6_GLYPH_COUNT;

	std::uint8_t m_text[2][TEXT_GLYPHS][mc6847_charset::GLYPH_HEIGHT]{};
	std::uint8_t m_semigraphics4[SEMIGRAPHICS4_GLYPHS * mc6847_charset::GLYPH_HEIGHT]{};
	std::uint8_t m_semigraphics6[SEMIGRAPHICS6_GLYPHS * mc6847_charset::GLYPH_HEIGHT]{};
};

struct character_ram_row_result
{
	bool valid = false;
	std::uint8_t character = 0;
	std::uint8_t row = 0;
	std::uint16_t address = INVALID_CAPTURE_ADDRESS;
	std::uint8_t bits = 0;
};

struct character_row_result
{
	bool valid = false;
	bool character_ram_requested = false;
	bool character_ram_used = false;
	bool inverted = false;
	character_layout layout = character_layout::NATIVE_32;
	character_glyph glyph = character_glyph::NONE;
	character_source source = character_source::NONE;
	std::uint8_t stream_byte = 0;
	std::uint8_t character = 0;
	std::uint8_t row = 0;
	std::uint16_t character_ram_address = INVALID_CAPTURE_ADDRESS;
	std::uint8_t bits = 0;
};

struct w64_cell_location
{
	bool valid = false;
	std::uint8_t text_row = 0;
	std::uint8_t text_column = 0;
	std::uint16_t capture_address = INVALID_CAPTURE_ADDRESS;
	std::uint8_t capture_row = 0;
	std::uint8_t capture_column = 0;
	std::uint16_t first_host_line = 0;
	std::uint16_t last_host_line = 0;
};
struct w64_pixel_location
{
	bool valid = false;
	w64_cell_location cell;
	std::uint8_t glyph_row = 0;
	std::uint8_t glyph_column = 0;
	std::uint8_t glyph_mask = 0;
};

struct vg6_pixel_location
{
	bool valid = false;
	std::uint8_t logical_x = 0;
	std::uint8_t logical_y = 0;
	std::uint16_t capture_address = INVALID_CAPTURE_ADDRESS;
	std::uint16_t capture_row = 0;
	std::uint8_t capture_column = 0;
	std::uint8_t nibble_shift = 0;
};

struct vg6_pixel_result
{
	bool valid = false;
	vg6_pixel_location location;
	std::uint8_t packed_byte = 0;
	std::uint8_t pixel = 0;
	bool css = false;
	std::uint8_t palette_index = 0;
	render_pixel color = 0;
};

struct extended_result
{
	extended_status status = extended_status::OK;
	extended_mode mode = extended_mode::NONE;
	std::uint64_t generation = 0;
	std::uint32_t pixels_written = 0;
	std::uint16_t scanlines_written = 0;

	bool success() const noexcept { return status == extended_status::OK; }
};

class extended_renderer
{
public:
	explicit extended_renderer(character_generator const &font) noexcept
		: m_font(&font)
	{
	}

	static extended_mode selected_mode(core const &control) noexcept;

	static character_ram_row_result lookup_character_ram(
			core const &control,
			std::uint8_t character,
			std::uint8_t row) noexcept;

	static w64_cell_location map_w64_cell(
			std::uint8_t text_row,
			std::uint8_t text_column) noexcept;

	// Coordinates are relative to the 512x384 viewport.
	static w64_pixel_location map_w64_viewport_pixel(
			std::uint16_t viewport_x,
			std::uint16_t viewport_y) noexcept;

	// Coordinates are relative to the 512x384 viewport.
	static vg6_pixel_location map_vg6_viewport_pixel(
			std::uint16_t viewport_x,
			std::uint16_t viewport_y) noexcept;

	static vg6_pixel_result decode_vg6_viewport_pixel(
			core const &control,
			frame_buffer_state const &frame,
			std::uint16_t viewport_x,
			std::uint16_t viewport_y) noexcept;

	static extended_status preflight(
			extended_mode mode,
			core const &control,
			frame_buffer_state const &frame) noexcept;

	static char const *status_name(extended_status status) noexcept;

	// Drawing, which needs the attached character generator.
	std::uint8_t text_character_row(
			bool t1_font,
			std::uint8_t character,
			std::uint8_t row) const noexcept;

	character_row_result resolve_character_row(
			core const &control,
			captured_cell const &cell,
			std::uint8_t row,
			character_layout layout) const noexcept;

	extended_result render(
			extended_mode mode,
			core const &control,
			frame_buffer_state const &frame,
			pixel_surface const &surface) const noexcept;

	extended_result render_scanline(
			extended_mode mode,
			core const &control,
			frame_buffer_state const &frame,
			std::uint16_t output_row,
			pixel_scanline const &scanline) const noexcept;

private:
	static extended_status preflight_scanline(
			extended_mode mode,
			core const &control,
			frame_buffer_state const &frame,
			std::uint16_t output_row) noexcept;

	static void render_vg6_scanline(
			core const &control,
			frame_buffer_state const &frame,
			std::uint16_t output_row,
			render_pixel *pixels) noexcept;

	void render_w64_scanline(
			core const &control,
			frame_buffer_state const &frame,
			std::uint16_t output_row,
			render_pixel *pixels) const noexcept;

	character_generator const *m_font;
};

static_assert(std::is_trivially_copyable<character_row_result>::value);
static_assert(std::is_standard_layout<character_row_result>::value);
static_assert(std::is_trivially_copyable<extended_result>::value);
static_assert(std::is_standard_layout<extended_result>::value);

} // namespace cocovga

#endif // MAME_VIDEO_COCOVGA_EXTENDED_H
